import { GetStaticProps } from "next";
import Head from "next/head";
import About from "../Components/About";
import Contacts from "../Components/Contacts";
import Hero from "../Components/Hero";
import NavBar from "../Components/NavBar";
import Skills from "../Components/Skills";
import Projects from "../Components/Projects";
import { WorkExperience, PageInfo, Project, Skill, Social } from "../typings";
import {
  getSocialData,
  getSkillsData,
  getPageInfoData,
  getExperienceData,
  getProjectsData,
} from "../utils/fetch";
import TimeLine from "../Components/TimeLine";

type Props = {
  pageInfo: PageInfo[];
  experiences: WorkExperience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[];
};

export default function Home({
  socials,
  skills,
  pageInfo,
  experiences,
  projects,
}: Props) {
  return (
    <div className="bg-teal-900 h-screen snap-y snap-mandatory overflow-scroll overflow-x-hidden z-0">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar social={socials} />

      <section id="hero" className="snap-center">
        <Hero pageInfo={pageInfo} />
      </section>
      <section id="about" className="snap-start">
        <About pageInfo={pageInfo} />
      </section>
      <section id="experience" className="snap-center">
        <TimeLine experience={experiences} />
      </section>
      <section id="skills" className="snap-center">
        <Skills skill={skills} />
      </section>
      <section id="projects" className="snap-center">
        <Projects project={projects} />
      </section>
      <section id="contacts" className="snap-center">
        <Contacts />
      </section>
    </div>
  );
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const socials: Social[] = await getSocialData();
  const skills: Skill[] = await getSkillsData();
  const pageInfo: PageInfo[] = await getPageInfoData();
  const experiences: WorkExperience[] = await getExperienceData();
  const projects: Project[] = await getProjectsData();
  return {
    props: {
      socials,
      skills,
      pageInfo,
      experiences,
      projects,
    },
  };
};
